server:
  port: 8080
spring:
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simple?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: simple
    password: 123456
mybatis:
  type-aliases-package: com.shuimutong.learn.mybatis.domain
  mapperLocations: classpath:mapper/*.xml